services:
  dynamodb-local:
    image: amazon/dynamodb-local:latest
    container_name: loopr-dynamodb-local
    command: '-jar DynamoDBLocal.jar -sharedDb -inMemory -port 8000'
    ports:
      - '127.0.0.1:8001:8000'
      